server:
  port: 8080
spring:
  # 数据源配置
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/abao2?useSSL=false&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    druid:
      initial-size: 2
      max-active: 10
      max-wait: 60000
      min-idle: 5
      validation-query: SELECT 1
      validation-query-timeout: 3000
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      #ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        #物理层的策略，如果有驼峰大写字母，则在大写字母前面插入_,同时大写字母变为小写字母，若没有则不处理
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  #    properties:
  #      hibernate:
  #        dialect: org.hibernate.dialect.MySQL5Dialect
  application:
    name: algorithm-test-all
  #邮箱配置
  mail:
    host: smtp.cheche365.com
    #阿里云和华为云不支持25端口，改用ssl的465端口
    port: 465
    username: abao-baodan@cheche365.com
    password: Cheche1234
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          port: 465
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true
            required: true
  #  cache:
  #    type: ehcache
  #    ehcache:
  #      config: classpath:/cache/ehcache-local.xml
  redis:
    #redis 索引，默认为0
    database: 1
    host: 192.168.2.81
    port: 6379
    #redis连接密码，默认为空
    password:
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 1000
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        min-wait: -1
        #连接池中的最大空闲连接
        max-idle: 10
        #连接池中的最小空闲连接
        min-idle: 2
    timeout: 200
  #websocket:
  #  url: ws://localhost:8080/websocket
  freemarker:
    cache: false
    charset: UTF-8
    content-type: text/html
    suffix: .ftl
    template-loader-path: classpath:/templates
  #mvc:
  #  static-path-pattern: /**
  #resources:
  #  static-locations: /static/
crm:
  resource:
    file-root-path: D:/test/nginx/
    url-root-path: /sr/itg/crm/
galaxy:
  redisson:
    codec: org.redisson.codec.FstCodec
    threads: 5
    nettyThreads: 5
    transportMode: NIO
    lockWatchdogTimeout: 3000
    model: "SINGLE"
    singleServerConfig:
      idleConnectionTimeout: 10000
      connectTimeout: 10000
      timeout: 3000
      retryAttempts: 3
      retryInterval: 1500
      password: null
      subscriptionsPerConnection: 5
      clientName: "redis1"
      address: "redis://192.168.2.81:6379"
      subscriptionConnectionMinimumIdleSize: 1
      subscriptionConnectionPoolSize: 50
      connectionMinimumIdleSize: 24
      connectionPoolSize: 64
      database: 0
      dnsMonitoringInterval: 5000
    sentinelServersConfig:
      idleConnectionTimeout: 10000
      connectTimeout: 10000
      timeout: 3000
      retryAttempts: 3
      retryInterval: 1500
      failedSlaveReconnectionInterval: 3000
      failedSlaveCheckInterval: 60000
      password: null
      subscriptionsPerConnection: 5
      clientName: null
      loadBalancer: org.redisson.connection.balancer.RoundRobinLoadBalancer
      subscriptionConnectionMinimumIdleSize: 1
      subscriptionConnectionPoolSize: 50
      slaveConnectionMinimumIdleSize: 24
      slaveConnectionPoolSize: 64
      masterConnectionMinimumIdleSize: 24
      masterConnectionPoolSize: 64
      readMode: "SLAVE"
      subscriptionMode: "SLAVE"
      sentinelAddresses:
        - "redis://127.0.0.1:26379"
        - "redis://127.0.0.1:26389"
      masterName: "mymaster"
      database: 0
    masterSlaveServersConfig:
      idleConnectionTimeout: 10000
      connectTimeout: 10000
      timeout: 3000
      retryAttempts: 3
      retryInterval: 1500
      failedSlaveReconnectionInterval: 3000
      failedSlaveCheckInterval: 60000
      password: null
      subscriptionsPerConnection: 5
      clientName: null
      loadBalancer: org.redisson.connection.balancer.RoundRobinLoadBalancer
      subscriptionConnectionMinimumIdleSize: 1
      subscriptionConnectionPoolSize: 50
      slaveConnectionMinimumIdleSize: 24
      slaveConnectionPoolSize: 64
      masterConnectionMinimumIdleSize: 24
      masterConnectionPoolSize: 64
      readMode: "SLAVE"
      subscriptionMode: "SLAVE"
      slaveAddresses:
        - "redis://127.0.0.1:6381"
        - "redis://127.0.0.1:6380"
      masterAddress: "redis://127.0.0.1:6379"
      database: 0
#    proxyServersConfig:
#    replicatedServersConfig：
#    clusterServersConfig: